package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sdl_gl_interface",
    srcs = ["sdl_gl_interface.cc"],
    hdrs = ["sdl_gl_interface.h"],
    linkstatic = 1,
    deps = [
        "//third_party:sdl_helper",
        "//util/graphics:gl_interface",
    ],
)
