package(default_visibility = ["//visibility:public"])

cc_library(
    name = "signal_scope",
    hdrs = ["signal_scope.h"],
    deps = [
        "//util:logging",
        "//util:math",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/strings",
        "@implot",
    ],
)
