load("//shader:shader_defs.bzl", "shader_cc_library")

package(default_visibility = ["//:__subpackages__"])

shader_cc_library(
    name = "blit_fsh",
    srcs = ["blit.fsh"],
)

shader_cc_library(
    name = "blit_vsh",
    srcs = ["blit.vsh"],
)
