load("//preset:preset_defs.bzl", "shader_cc_library")

package(default_visibility = ["//:__subpackages__"])

shader_cc_library(
    name = "math",
    hdrs = ["math.shh"],
)

shader_cc_library(
    name = "complex",
    hdrs = ["complex.shh"],
)
