package(default_visibility = ["//:__subpackages__"])

cc_library(
    name = "perspective",
    hdrs = ["perspective.h"],
    srcs = ["perspective.cc"],
)

cc_library(
    name = "vector",
    hdrs = ["vector.h"],
    srcs = ["vector.cc"],
)
