cc_library(
    name = "logging",
    hdrs = ["logging.h"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "colors",
    srcs = ["colors.cc"],
    hdrs = ["colors.h"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
