control_mappings {
  key: "transition_input"
  value: "control_change:3:1:0"
}
control_mappings {
  key: "zoom_vec_x"
  value: "control_change:3:2:0"
}
control_mappings {
  key: "zoom_vec_y"
  value: "control_change:3:3:0"
}
control_mappings {
  key: "zoom_vec_z"
  value: "control_change:3:4:0"
}
signals_by_name {
  key: "space_whale_eye_warp_border_hue_coeff"
  value {
    low: 0
    high: 3
  }
}
signals_by_name {
  key: "space_whale_eye_warp_border_value_coeff"
  value {
    low: 0
    high: 1
  }
}
signals_by_name {
  key: "transition_input"
  value {
    low: -1
    high: 1
  }
}
signals_by_name {
  key: "zoom_vec_x"
  value {
    low: -1
    high: 1
  }
}
signals_by_name {
  key: "zoom_vec_y"
  value {
    low: -1
    high: 1
  }
}
signals_by_name {
  key: "zoom_vec_z"
  value {
    low: -1
    high: 1
  }
}
counters_by_name {
  key: "model_to_draw"
  value {
    low: 0
    high: 5
    value: 5
  }
}
counters_by_name {
  key: "next_preset"
  value {
    low: 0
    high: 0
    value: 0
  }
}
controls_by_name {
  key: "control_change:3:0:0"
  value: 0.496063
}
controls_by_name {
  key: "control_change:3:1:0"
  value: 0.496063
}
controls_by_name {
  key: "control_change:3:2:0"
  value: 0.307086617
}
controls_by_name {
  key: "control_change:3:3:0"
  value: 0.566929162
}
controls_by_name {
  key: "control_change:3:4:0"
  value: 0.629921257
}
controls_by_name {
  key: "control_change:4:0:0"
  value: 0.496063
}
controls_by_name {
  key: "control_change:4:2:0"
  value: 0.314960629
}
controls_by_name {
  key: "control_change:4:3:0"
  value: 0.574803174
}
controls_by_name {
  key: "control_change:4:4:0"
  value: 0.637795269
}
