load("@py_deps//:requirements.bzl", "requirement")

py_binary(
    name = "filter_explorer",
    srcs = ["filter_explorer.py"],
    deps = [
        requirement("matplotlib"),
        requirement("numpy"),
    ],
)
