name: Build/Test
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Install C++ dependencies
      run: |
        sudo apt-get install -y -qq libpulse-dev libgl-dev libglm-dev libsdl2-dev libncurses5-dev libncurses5
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Build (Host, GCC)
      run: ./run_libopendrop.sh -z
    - name: Test (Host, GCC)
      run: ./run_libopendrop.sh -t
    - name: Build (Host, Clang)
      run: ./run_libopendrop.sh -z -c clang
    - name: Test (Host, Clang)
      run: ./run_libopendrop.sh -t -c clang
    - name: Build (Raspberry Pi, Clang)
      run: ./run_libopendrop.sh -z -c pi
