name: Host Build/Test (GCC)
on: [push, pull_request]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Install C++ dependencies
      run: |
        sudo apt-get install -y -qq libpulse-dev libgl-dev libglm-dev libsdl2-dev libncurses5-dev libncurses5
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Build
      run: bazelisk build //:main --copt=-I/usr/include/SDL2 --copt=-std=c++17
    - name: Test
      run: bazelisk test ... --copt=-I/usr/include/SDL2 --copt=-std=c++17 --test_output=streamed
