name: Build/Test
on: [push, pull_request]
jobs:
  setup_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Update installation
      run: |
        sudo apt-get update
    - name: Install C++ dependencies
      run: |
        sudo apt-get install -y -qq libpulse-dev libgl-dev libglm-dev libsdl2-dev libncurses5-dev libncurses5 lcov
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Build (Host, GCC)
      run: ./run_libopendrop.sh -z
    - name: Test (Host, GCC)
      run: ./run_libopendrop.sh -t
    - name: Coverage (Host, GCC)
      run: |
        bazelisk coverage --combined_report=lcov //...
        genhtml --output genhtml "$(bazelisk info output_path)/_coverage/_coverage_report.dat"
        #- name: Build (Host, Clang)
        #  run: ./run_libopendrop.sh -z -c clang
        #- name: Test (Host, Clang)
        #  run: ./run_libopendrop.sh -t -c clang
        #- name: Build (Raspberry Pi, Clang)
        #  run: ./run_libopendrop.sh -z -c pi
        #- name: Upload coverage report
        #  uses: actions/upload-artifact@v3
        #  with:
        #    name: lcov-report
        #    path: genhtml/
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./bazel-out/_coverage/_coverage_report.dat"
