name: Build/Test
on:
  pull_request:
  push:
    branches:
      - 'master'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Update installation
      run: |
        sudo apt-get update
    - name: Install C++ dependencies
      run: |
        sudo apt-get install -y -qq libpulse-dev libgl-dev libglm-dev libsdl2-dev libncurses5-dev libncurses5 lcov
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Coverage (Host, GCC)
      run: |
        bazelisk coverage --combined_report=lcov //...
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./bazel-out/_coverage/_coverage_report.dat"
    - name: Build (Host, GCC)
      run: ./run_libopendrop.sh -z --profile=/tmp/profile_gcc_host.gz
    - name: Upload build profile (Host, GCC)
      uses: actions/upload-artifact@v3
      with:
        name: profile-gcc-host
        path: /tmp/profile_gcc_host.gz
    - name: Test (Host, GCC)
      run: ./run_libopendrop.sh -t
    - name: Build (Host, Clang)
      run: ./run_libopendrop.sh -z -c clang --profile=/tmp/profile_clang_host.gz
    - name: Upload build profile (Host, Clang)
      uses: actions/upload-artifact@v3
      with:
        name: profile-clang-host
        path: /tmp/profile_clang_host.gz
    - name: Test (Host, Clang)
      run: ./run_libopendrop.sh -t -c clang
    - name: Build (Raspberry Pi, Clang)
      run: ./run_libopendrop.sh -z -c pi --profile=/tmp/profile_clang_rpi.gz
    - name: Upload build profile (Raspberry Pi, Clang)
      uses: actions/upload-artifact@v3
      with:
        name: profile-clang-rpi
        path: /tmp/profile_clang_rpi.gz
