name: Build/Test
on: [push, pull_request]
jobs:
  setup_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Update installation
      run: |
        sudo apt-get update
    - name: Install C++ dependencies
      run: |
        sudo apt-get install -y -qq libpulse-dev libgl-dev libglm-dev libsdl2-dev libncurses5-dev libncurses5 lcov
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel
  build_host_gcc:
    needs: setup_workflow
    runs-on: ubuntu-latest
    steps:
    - name: Build (Host, GCC)
      run: ./run_libopendrop.sh -z
  test_host_gcc:
    needs: build_host_gcc
    runs-on: ubuntu-latest
    steps:
    - name: Test (Host, GCC)
      run: ./run_libopendrop.sh -t
  build_host_clang:
    needs: setup_workflow
    runs-on: ubuntu-latest
    steps:
    - name: Build (Host, Clang)
      run: ./run_libopendrop.sh -z -c clang
  test_host_clang:
    needs: build_host_clang
    runs-on: ubuntu-latest
    steps:
    - name: Test (Host, Clang)
      run: ./run_libopendrop.sh -t -c clang
  coverage_host_gcc:
    needs: setup_workflow
    runs-on: ubuntu-latest
    steps:
    - name: Coverage (Host, GCC)
      run: |
        bazelisk coverage --combined_report=lcov //...
        genhtml --output genhtml "$(bazelisk info output_path)/_coverage/_coverage_report.dat"
    - uses: actions/upload-artifacts@v3
      with:
        name: lcov-report
        path: genhtml/
  build_rpi_clang:
    needs: setup_workflow
    runs-on: ubuntu-latest
    steps:
    - name: Build (Raspberry Pi, Clang)
      run: ./run_libopendrop.sh -z -c pi
